#!/bin/bash

gcc -fpic -O2 -std=gnu99 -Wall -c -o entities.o entities.c
gcc -I/usr/include/libpurple -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -fpic -O2 -std=gnu99 -Wall -c -o stfw.o stfw.c
gcc -shared -fpic -lglib-2.0 -lpurple -o stfw.so stfw.o entities.o


